CREATE TABLE USERMANAGEMENT (
    USERNAME VARCHAR(64) NOT NULL,
    USERID VARCHAR(64) NOT NULL,
    USERPW VARCHAR(64) NOT NULL,
    ACCOUNTCREATE DATE NOT NULL
);

/*テーブルコメント*/
COMMENT ON TABLE USERMANAGEMENT IS 'ユーザデータ管理';

/*テーブルカラムコメント*/
COMMENT ON COLUMN USERMANAGEMENT.USERNAME IS 'ユーザ名';
COMMENT ON COLUMN USERMANAGEMENT.USERID IS 'ユーザID';
COMMENT ON COLUMN USERMANAGEMENT.USERPW IS 'ユーザPW';
COMMENT ON COLUMN USERMANAGEMENT.ACCOUNTCREATE IS 'アカウント作成日';
